#!/bin/bash

#unset proxy variable
export http_proxy=
key=$(<../key)


# Make Request to Toolkit to indicate current state of execution
trap catch_errors ERR;
function catch_errors() {
    echo "error" >> ../results/process.log
    curl -X POST http://%HOSTNAME:%PORT/jobs/error/%jobid.content/$key
    echo "script aborted, because of errors"
    exit 0
}
curl -X POST http://%HOSTNAME:%PORT/jobs/running/%jobid.content/$key > /dev/null 2>&1

# retrieve sge id

curl -X POST http://%HOSTNAME:%PORT/jobs/sge/%jobid.content/${JOB_ID} > /dev/null 2>&1

# Recreate results and log directories
rm -rf ../results
rm -rf ../logs

mkdir ../results
mkdir ../logs

# Set environment
source %ENVIRONMENT
